### ISSUE TITLE
Yard documentation is empty on rubydoc.info

### ISSUE THREAD

**Issue by gavinlaking** [gavinlaking/vedeu#130]
When attempting to view the documentation on rubydoc.info, annoyingly, an empty project appears.

This issue is due to a regression in Ruby itself, further details of which can be found here:

https://github.com/lsegal/yard/issues/825

In the meantime, cloning this repository, bundling and running `yard server` means you can access the documentation locally at `http://localhost:8808/`.

**Comment by IceDragon200** [comment]
http://www.rubydoc.info/gems/yard
http://www.rubydoc.info/github/lsegal/yard

I believe your issue has been resolved

**Comment by gavinlaking** [comment]
Having bumped the Ruby version to 2.2.1, and re-submitting the project to Rubydoc, the documentation is still not showing up. Visiting http://www.rubydoc.info/gems/vedeu seems to kick off the documentation regeneration process, but it just hangs. Will investigate further.

**Comment by gavinlaking** [comment]
Having just pushed a new version of the gem, I decided to hit RubyGems.org and then the documentation link there: (http://www.rubydoc.info/gems/vedeu/0.4.14), after a short wait the documentation built! I'll keep an eye on this, hopefully the issue is resolved now and so will close this. My apologies for the inconvenience.
